# Generated by Django 4.2.7 on 2024-07-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.CharField(blank=True, max_length=200)),
                ("named_url", models.CharField(blank=True, max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("menu_name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["menu_name", "order"],
                "unique_together": {("menu_name", "order")},
            },
        ),
    ]
